### ISSUE TITLE
Boolean values in Docker API

### ISSUE THREAD

**Issue by r0b1n** [stage1/docker-php#103]
While implementing isolated tests I have noticed some issues.
Docker API supports boolean values as `1/true/True` or `0/false/False` only (as well as doc says). Part of current implementation doesn't follows requirements, `false` becomes empty string in request `?force=&noprune=`.
I offer to cast these values to 0 or 1 explicitly.
https://github.com/r0b1n/docker-php/commit/aa51198bc6d110b187897a198dc558653384597d

**Comment by hacfi** [comment]
@r0b1n I agree that this should be fixed. They might prefer type casting though..see https://github.com/stage1/docker-php/blob/master/src/Docker/Docker.php#L133

**Comment by ubermuda** [comment]
Yup, these values should be type casted, don't hesitate to submit a PR :)

**Comment by joelwurtz** [comment]
closed in #147
