### ISSUE TITLE
composer refuses installation

### ISSUE THREAD

**Issue by olafWal** [stage1/docker-php#112]
- Updating stage1/docker-php (dev-master 1553a73 => v0.4.0)
    Checking out cba2d26bf95f14947555a07e65d6fc13f5a09ae8

                                                                               
  [RuntimeException]                                                           
  Failed to clone git@github.com:stage1/docker-php.git via git, https, ssh protocols, aborting.                                                           
  - git://github.com/stage1/docker-php.git                                     
    error: unable to resolve reference refs/remotes/composer/fix/travis: Not   
  a directory                                                                  
    From git://github.com/stage1/docker-php                                    
     ! [new branch]      fix/travis -> composer/fix/travis  (unable to update  
   local ref)                                                                  
    error: some local refs could not be updated; try running                   
     'git remote prune composer' to remove any old, conflicting branches       
  - https://github.com/stage1/docker-php.git                                   
    error: unable to resolve reference refs/remotes/composer/fix/travis: Not   
  a directory                                                                  
    From https://github.com/stage1/docker-php                                  
     ! [new branch]      fix/travis -> composer/fix/travis  (unable to update  
   local ref)                                                                  
    error: some local refs could not be updated; try running                   
     'git remote prune composer' to remove any old, conflicting branches       
  - git@github.com:stage1/docker-php.git                                       
    Permission denied (publickey).                                             
    fatal: Could not read from remote repository.                              
                                                                               
    Please make sure you have the correct access rights                        
    and the repository exists.

**Comment by ubermuda** [comment]
Can you post your `composer.json` please?

**Comment by olafWal** [comment]
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/", "SymfonyStandard": "app/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.5.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
	"knplabs/knp-menu-bundle":"@stable",
	"doctrine/migrations": "dev-master",
	"doctrine/doctrine-migrations-bundle": "dev-master",
	"friendsofsymfony/user-bundle": "~2.0@dev",
	"jms/security-extra-bundle": "dev-master",
	"sonata-project/intl-bundle": "dev-master",
	"oyejorge/less.php": "~1.5",
        "twitter/bootstrap": "dev-master",
	"friendsofsymfony/jsrouting-bundle": "@stable",
        "willdurand/js-translation-bundle": "@stable",
	"pinano/select2-bundle": "dev-master",
        "liip/imagine-bundle": "@stable",
	"stage1/docker-php": "@dev",
	"hpatoio/deploy-bundle": "dev-master",
	"egeloen/ckeditor-bundle": "~2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.5-dev"
        }
    }
}

**Comment by joelwurtz** [comment]
Go to vendor/stage1/docker-php and run `git remote prune composer` then rerun composer update / install, sometimes composer mess up with remote branch being deleted

**Comment by olafWal** [comment]
Already tried that, but:

```
olaf@beta:/srv/userdir/olaf/WebHero/vendor/stage1/docker-php$ git remote prune composer
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by olafWal** [comment]
Works for me now, deleting vendor/stage1 and runnning composer again fixed it.
