### ISSUE TITLE
Consider upgrading dependencies to guzzle 5?

### ISSUE THREAD

**Issue by jeremythorson** [stage1/docker-php#114]
Has there been any consideration/discussion around updating docker-php's dependencies to leverage a newer release of guzzle (i.e. ~5.*)?

I'm running into a dependency conflict with another library I'd like to use, and upgrading docker-php to support the newer version of guzzle seems a more rational ask than requesting that they downgrade.

**Comment by hacfi** [comment]
Hi @jeremythorson, there has been a discussion about this over at #46 but the development hasn’t started.

**Comment by joelwurtz** [comment]
duplicate of #46
