### ISSUE TITLE
Connection to Docker host with TLS enabled

### ISSUE THREAD

**Issue by meons** [stage1/docker-php#117]
Hello,

Actually I use docker-php lib in a Docker project and I have a problem with TLS connection. Error message is Connection refused (code 111).
![0](https://cloud.githubusercontent.com/assets/5362939/7798142/630ccf9a-02f6-11e5-9cd1-64b283eec391.png)

And there is the code http://pastebin.com/UNkpynyS (I followed the doc http://docker-php.readthedocs.org/en/latest/basic/)

It works fine without TLS and I can do API calls.

Does anyone ever encountered this problem ?

Thank you in advance

Regards,
S. Bobylev

**Comment by hacfi** [comment]
@meons Which OS, PHP and openssl version?

**Comment by meons** [comment]
Ubuntu 14.04.2 LTS
Docker client 1.4.1 / Docker API 1.16
PHP 5.5.9-1ubuntu4.5
OpenSSL 1.0.1f

**Comment by meons** [comment]
So am I the only one with this problem ?

**Comment by hacfi** [comment]
@meons I’m on OS X and creating a `comb.pem` fixed the issue (http://docker-php.readthedocs.org/en/latest/basic/).

Anyone else on Ubuntu having this issue?

**Comment by joelwurtz** [comment]
The error happens before tls is initialized, the bug must come from your host / port you set for the remote docker api or from something blocking the access (firewall, ...)

**Comment by joelwurtz** [comment]
Any new of this ? closing the issue for the moment don't hesitate to reopen it if you stille have this behavior.

**Comment by meons** [comment]
Sorry but I don't work anymore on this project so I dont' have the infrastructure for test. Anyway thanks for your answers =)
