### ISSUE TITLE
Docs Pointing to incorrect / Missing URL

### ISSUE THREAD

**Issue by drpain** [stage1/docker-php#123]
https://github.com/stage1/docker-php/blob/master/doc/usage.md on http://stage1.github.io/docker-php/

Should be changed to:
https://github.com/stage1/docker-php/blob/master/docs/basic.md

**Comment by ubermuda** [comment]
Thanks for pointing this, I updated the page with the latest README, including an updated documentation link to read the docs

**Comment by drpain** [comment]
Sure, I am keen to try your library out. Tnx for the speedy update!
