### ISSUE TITLE
Compatibility with last version of Guzzle

### ISSUE THREAD

**Issue by pvcnt** [stage1/docker-php#126]
Hello,

I did not read everything but would it be possible to integrate the latest version of Guzzle? It would make it possible to use docker-php in environments where Guzzle 6 is used.

Thanks.

**Comment by ubermuda** [comment]
We could easily check this by bumping guzzle's version and running the unit tests. The test suite is quite comprehensive and I'm confident any problem would be catched by it.

What do you think @joelwurtz ?

**Comment by joelwurtz** [comment]
duplicate of #46
