### ISSUE TITLE
Relying on dev/beta packages

### ISSUE THREAD

**Issue by Babacooll** [stage1/docker-php#149]
Hi,

With your release v0.5.0 you rely on many packages with non fixed versions. That is a big issue for projets using this. For example "jane/swagger" has no fixed version, any update on their side might brake your stuff.

Do you have any solution about that ?

**Comment by joelwurtz** [comment]
That's why it's still in 0.5 and not in 1.0.

You can still use the 0.4 version for the moment if you want something stable, or set minimum stability to dev. There will be stable release of jane/swagger and php-http before the end of this month, i will then update composer and tag a 1.0.

**Comment by Babacooll** [comment]
Well I don't think this is a good solution to tag a non-stable version. When you require a composer package you expect the last stable version which is not the case here.

But I'll use your 0.4 version, thank you for the answer.

**Comment by joelwurtz** [comment]
Fixed in the last version of master, new release soon :)
