### ISSUE TITLE
Goal to stable version

### ISSUE THREAD

**Issue by joelwurtz** [stage1/docker-php#30]
Here is a list of thing to do in order to achieve a first stable release : 

### Planning other apis

- [ ] Refactoring namespace and class name to handle other apis ? #26 

#### ContainerManager

- [x] List containers : GET /containers/json
- [x] Inspect a container : GET /containers/(id)/json
- [x] Create a container : POST /containers/create
- [x] Get logs from a container : GET /containers/{id}/logs
- [x] List processes runining inside a container : GET /containers/(id)/top
- [x] Inspect changes on a container’s filesystem : GET /containers/(id)/changes
- [x] Export a container : GET /containers/(id)/export 
- [x] Start a container : POST /containers/(id)/start 
- [x] Stop a container : POST /containers/(id)/stop
- [x] Restart a container : POST /containers/(id)/restart
- [x] Kill a container : POST /containers/(id)/kill
- [x] Attach to a container : POST /containers/(id)/attach
- [x] Wait a container : POST /containers/(id)/wait
- [x] Remove a container : DELETE /containers/(id)
- [ ] Copy files or folders from a container : POST /containers/(id)/copy
- [x] Support WebSocket protocol for attach api (not documented in RemoteApi but available, need to see docker source code and docker-py, docker client in python, has an implementation)
- [x] Create a new image from a container’s changes : POST /commit 
- [x] Create an exec process for a container : POST /containers/(id)/exec 
- [x] Start an exec process for a container : POST /exec/(id)/start 

#### ImageManager

- [x] Move api for image from Docker class to ImageManager class
- [x] List Images : GET /images/json 
- [x] Create an image : POST /images/create
- [x] Inspect an image : GET /images/(name)/json
- [x] Get the history of an image : GET /images/(name)/history
- [ ] Push an image on the registry : POST /images/(name)/push
- [x] Tag an image into a repository : POST /images/(name)/tag
- [x] Remove an image : DELETE /images/(name) 
- [x] Search images : GET /images/search
- [x] Build an image from Dockerfile : POST /build

#### Misc

- [ ] Check auth configuration : POST /auth
- [x] Display system-wide information : GET /info
- [ ] Monitor Docker’s events : GET /events
- [ ] Load a tarball with a set of images and tags into docker : POST /images/load
- [x] Show the docker version information : GET /version 

#### Utility function

- [x] Simulate a docker run
- [x] Allow to easy remove a bunch of containers / image (clean function ?)

### Guzzle 4

- [x] Take a decision on integration Guzzle 4 to Docker #25

**Comment by hacfi** [comment]
Misc -> Display system-wide information : GET /info
was added by @Boran in bb2cd19

**Comment by ubermuda** [comment]
Updated!

**Comment by hacfi** [comment]
Utility function > Allow to easy remove a bunch of containers / image (clean function ?)
was added by #84

**Comment by ubermuda** [comment]
Checked! Thanks

**Comment by joelwurtz** [comment]
Add exec function

**Comment by joelwurtz** [comment]
closed in #147
