### ISSUE TITLE
New structure proposal

### ISSUE THREAD

**Issue by gsouf** [stage1/docker-php#46]
Everything is available in my fork : https://github.com/SneakyBobito/docker-php but please read the following before.

Introduction
=========
I have a proposal for a new way to implement commands in docker-php. I think that such a way would allow to make it really easyer to implement. It is also more semantic and much more clean.

It is though to be 100% extendable and rewrittable by extending classes. Then even the most complexe api endpoint that mays need complexe stuff can be implemented in this way.

Please be aware that this will break a few compatibility with previous versions.

No test has been written or updated for the moment

About the new command structure
=================================

Each command is one class. The class is named to reflect the api endpoint. 

E.G ``POST /containers/create`` is available through the class ``Docker\Command\Post\Containers\Create``

Each of these classes extend ``Docker\Command\AbstractCommand`` : https://github.com/SneakyBobito/docker-php/blob/master/src/Docker/Command/AbstractCommand.php

It offers a common way to call them for a given docker instance. ``$command->run($dockerInstance);``

The run command returns an object that wraps the request, the response and an ouput specific to the command. If an error happens, then it returns an exception

I placed a little doccumentation about this implementation. Not sure it is very understandable at the first reading but it allows to have all in one place :  
https://github.com/SneakyBobito/docker-php/blob/master/doc/internal/command.md

What did i change too
=================

* I added the property ``apiVersion`` to the ``Docker\Docker`` class. That allows to build such url : ``/v1.10/containers/create``
 
* I changed the constructor of ``Docker\Manager\ContainerManager`` to pass the docker instance instead of the docker client. Then it allows to call the new command structure directly from the Manager (because commands need a Docker\Docker instance, and not a http client instance) 

Please if something is obscure to you feel free to ask me.

**Comment by SneakyBobito** [comment]
@ubermuda do you want this proposition in the future or should the issue be closed ?

**Comment by joelwurtz** [comment]
IMO, i'm +10000 for this architecture IF it's based on this library https://github.com/egeloen/ivory-http-adapter and PSR-7 https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md

**Comment by ubermuda** [comment]
@SneakyBobito actually I've been thinking about this a lot lately, and I like the idea, so we should definitely keep this issue around

@joelwurtz I'm not sure how this is new architecture is related to the http adapter?

**Comment by joelwurtz** [comment]
Not specifically related, but implementing this new architecture will need a heavy rewrite of the core of docker-php, if we are doing this i would like to use this refactoring to also implements PSR-7 by using this http-adapter

**Comment by SneakyBobito** [comment]
@ubermuda ok, are you ready to upgrade the library to an upper major version ? If yes i'm free to work on it.

@joelwurtz not sure about PSR-7, the http adapter handles it. The library should not even be aware that it exists. The library wants to deal with a docker instance. Actually I'm not sure to understand what you want with psr7.
I think that ivory http can be a good think, then people are free to choose what they want. But i'm not sure it's related to this issue

**Comment by ubermuda** [comment]
I'm all for working on this yes, especially since we have a pretty good test coverage. This could be the final milestone on the road to 1.0. The public API would need to stay the same though (not for BC reason)

**Comment by hacfi** [comment]
Should we create a branch/repo to get the development started? I’ll do my best to help out as much as possible.

**Comment by ubermuda** [comment]
I'm not sure what's the best way to organize this. I was thinking creating a branch on which refactoring can be based, what do you think?

**Comment by hacfi** [comment]
I was thinking the same. All related issues/PRs should use some kind of [label/title] in the title.

**Comment by ubermuda** [comment]
All right, I just created the `new-structure` branch and the `newstruct` label. I might not have much time to contribute code, but I will be following this as closely as I can (or you can ping @joelwurtz if I'm not slow)

**Comment by SneakyBobito** [comment]
For the issues, just use the milestone feature of github

**Comment by joelwurtz** [comment]
Hey,

I'm actually writing an api client generator which is inspired of the guzzle-services by using the swagger specification (2.0)

This tool is not done yet but i'm actually, for the coming days, at full time on it as we will use it for some projects in our agency, and also for open source projetcs.

The principle is simple, we only write the swagger specification and the tool will generate an api client compatible with PSR7 Request / Response standard and abstract the HTTP client by using this library https://github.com/egeloen/ivory-http-adapter

The tool is separated in two (different purpose) : 

 * [jane/jane](https://github.com/jolicode/jane) : which generated a Object Model in PHP, and the normalizer services to be used with the [symfony/serializer](http://symfony.com/doc/current/components/serializer.html) component from a JSON Schema

* [jane/jane-swagger](https://github.com/jolicode/jane) : which extends Jane with the swagger specification to generate a Client API

You can see on this repository https://github.com/jolicode/jane-swagger-example-docker an example on how the client will be generated (this is a early preview, it does not work out of the box for the moment)

The goal is too have less maintenance required on our part as we can follow the rythm of docker evolution (only have to maintain the swagger specification, and the hijack part, like the raw stream)

And also docker planned to expose it's api with the swagger specification as you can see on this issue : https://github.com/docker/docker/pull/16125

Let met know what you think, cheers 

(poke @ubermuda :heart: )

**Comment by ubermuda** [comment]
I like that very much.

If we're able to generate the plumbing of the library automatically, we can then focus on adding the porcelain layer that will make it feel more like a PHP library and make it easier and more intuitive to use.

**Comment by joelwurtz** [comment]
See #147

**Comment by joelwurtz** [comment]
closed in #147
