### ISSUE TITLE
ImageManager refers to undefined StreamCallbackInterface

### ISSUE THREAD

**Issue by hacfi** [stage1/docker-php#74]
https://github.com/stage1/docker-php/blob/master/src/Docker/Manager/ImageManager.php#L49 refers to `Docker\Http\Stream\StreamCallbackInterface` which doesn’t exist.

**Comment by hacfi** [comment]
Just discovered that the branches [`feature/chunk_stream_filter`](https://github.com/stage1/docker-php/tree/feature/chunk_stream_filter/src/Docker/Http/Stream) and [`sneakybobito/structure`](https://github.com/stage1/docker-php/tree/sneakybobito/structure/src/Docker/Http/Stream) contain the class so it looks like some feature wasn’t merged (yet?).

**Comment by hacfi** [comment]
I’d be happy to fix this but need to know what the status is. @ubermuda Do you know more about this?

**Comment by joelwurtz** [comment]
It's a bug, this Interface was removed as it does not make sense anymore just removing the condition will be good.

**Comment by hacfi** [comment]
@joelwurtz Thanks for the confirmation..created #80
