### ISSUE TITLE
ContainerManager: functions should return response, not $this

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#75]
Hi,

functions such as create() start() wait() stop() remove() return a ContainerManager object, but it would be more useful to return $response. 
There does not seem to be much point in returning the manager and access to the response code and body can be important for flow control/debugging

restart() and kill() could also return $response

What do you think? I can create a pull request once we have agreed.

**Comment by ubermuda** [comment]
I am against this, for multiple reasons. In order of importance (most important to less):

1. That is not the philosophy of Docker-PHP. The goal of this library is to create an workable abstraction of the Docker API. Most other Docker libraries I've used are mostly soul-less 1:1 mapping to the API, without any regard whatsoever for the specificities of the language it is written with, or what the API is representing at all, effectively forcing users to *learn* the Docker API with all its inconsistencies. Docker-PHP aims to be a library that makes sense for PHP developers.

2. The response object is an implementation detail. Even if (and that's a HUGE if) we were to return anything else than a ContainerManager from these methods, it would have to be an abstraction too (a `DockerAPIResponse` for example), but the Container object is already supposed to be that abstraction.

3. The fluent interface allows fluid programming and that would be a huge BC break. I know Docker-PHP isn't even 1.0 and we shouldn't bother about BC breaks, but I want to be able to write code like this:
 
    ```php
    $container = new Container(['Image' => 'nginx']);
    
    $manager
        ->create($container)
        ->start($container);
    ```

**Comment by ubermuda** [comment]
Also, you should be able to do flow control with the informations stored inside the Container object (which I think you can do in the current state of Docker-PHP), and to do error management by handling the Exceptions (which needs more work to be fully doable).

**Comment by ubermuda** [comment]
As for debugging, I think we need to inject a Logger into the Managers.

**Comment by Boran** [comment]
Ah, that is very nice and makes sense, didn't realise one could chain like that. elegant.
I do have unusual behavior on one docker server that I'm trying to debug (server error 500), hence my need to access $response. 

In your example above I also do, between new() and create()
$container->setName('some name');

**Comment by ubermuda** [comment]
We'll add some logging ability to help debugging
