### ISSUE TITLE
following logs in realtime with logs() or attach() ?

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#76]
This allows that last 20 lines of the container logs to be gathered into $logs:
$logs=$manager->logs($container, false, true, true, false, 20);

I'd like to tail the logs but stay attached and print new entries as they arrive. So tried setting the first argument $follow=true. But nothing gets printed, and it just waits.
$logs=$manager->logs($container, true, true, true, true, 20);
Also tried
$logs=$manager->logs($container, true, true, true);

Perhaps the attach() is what is needed, looking at usage.md it suggests:
$manager->attach($container)->getBody()->readWithCallBack(function($output, $type) {
    print($output);
});
but that gives "Argument 2 .. must be callable"

and found this to work
$response=$manager->attach($container, function ($output, $type) {print($output);} , true);
$response->getBody()->getContents();

or:
$manager->attach($container, function ($output, $type) {print($output);} , true)->getBody()->getContents();

Then tried that in a web page, but have been unable to get realtime line by line output despite things like
    ini_set('output_buffering', 'off');
    ini_set('zlib.output_compression', false);
    ini_set('implicit_flush', true);
    ob_implicit_flush(true);
but that is another story

So I guess my question is what is the recommended way of tailing the logs in real time (example to update in usage.md?).

**Comment by hacfi** [comment]
@Boran No idea if that will work but my recommendation is to first test this as a php cli command before you try to pass the output to a browser. PHP is not the ideal tool for piping logs to a browser. If it works as a cli command you should have a look at http://elephant.io/ which might make piping easier.

**Comment by Boran** [comment]
Yes, cli testign is best.

should the Usage.md doc be update to:

$manager->attach($container, function ($output, $type) {print($output);} , true)->getBody()->getContents();

or:

$response=$manager->attach($container, function ($output, $type) {print($output);} , true);
$response->getBody()->getContents();

**Comment by ubermuda** [comment]
Actually I guess if you pass the callback you don't need the `->getBody()->getContents()` part. I'll check that and update the `usage.md` accordingly.

**Comment by Boran** [comment]
I've created two example copy/paste scripts, one that uses curl directly on the api, the other using docker/php. It saves me quite a bit of time when learning/using both apis, as one may not use a function for a month or two and then have forgotten how to use it exactly.
It your are interested I can create a PR so you can look at them.
