### ISSUE TITLE
docker exec equivalent? POST /containers/(id)/exec

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#77]
Is there a way in docker-php to do run  a command within a container, the equivalent of:
docker exec mycontainer sh -c 'cd /var/www/html; git status'

via the API: POST /containers/(id)/exec 
http://docs.docker.com/reference/api/docker_remote_api_v1.16/#exec-create

There is no equivalent yet in ContainerManager.php ?

**Comment by hacfi** [comment]
This feature was introduced in Docker Remote API v1.15 and is not included in `docker-php` yet. Feel free to create a PR for this..I’m sure others would like to use this as well!

**Comment by joelwurtz** [comment]
Like @hacfi there is no equivalent in docker-php, but normally all the tool are present to facilitate the creation of this api (InteractiveStream and Callback filtering)

**Comment by Boran** [comment]
Yes I'll create a PR.
FYI a simple example using the docker API directly: With a running Ubuntu container named "vanilla2", execute the "date" command:

curl -X POST -H "Content-Type: application/json" http://127.0.0.1:2375/containers/vanilla2/exec -d '{ "AttachStdin":false,"AttachStdout":true,"AttachStderr":true, "Tty":false, "Cmd":["/bin/date"] }'

{"Id":"213f4f0abd592b302a6af43637f4422f6387b63a9759643b3e6024655099b298"}

curl -X POST -H "Content-Type: application/json" http://127.0.0.1:2375/exec/213f4f0abd592b302a6af43637f4422f6387b63a9759643b3e6024655099b298/start -d '{ "Detach":false,"Tty":false}'

**Comment by Boran** [comment]
Closing this see PR #90
