### ISSUE TITLE
ImageManager::inspect()

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#78]
First, small, typo in the header
this:
     * @return ImageManager
shoule be something like
     * @return json data from docker inspect, $image[id] is also set

further down in that function:
        $image->setId($data['Id']);
        // @TODO Add extra info on image
Why is the Id writteen again, and what is meant by that TODO, what extra info do you want stored? Did you also want to "re-write" the repo and tag, incase the $image variable is stale?

(I can create a  pull request one it has been agreed on what to do)

**Comment by ubermuda** [comment]
> Why is the Id writteen again

IIRC what I was doing when I initially wrote this, `ImageManager::inspect` was meant to be used on images that have a `repository` set (and possibly a `tag`). It was not expected to work with a plain image id. When #79 is merged, everything will change, so this will need a fix too I guess.

So yes, I think re-writing the repository and tag too would be good, unless you have something better to propose to be sure the `Image` object has all the information (id + repository + tag)

**Comment by Boran** [comment]
I dont think it should set any of these, inspect() should just analyse and report back.
If inspect() gets an image with an id, it uses that. It should not need to change it. The json from docker is hardly going to come back with a different id?

Ah. Usually one does a find() first, which creates the image object, setting repo+tag. Then in find() one calls inspect. 
Perhaps it would be more logical to have the $image->setId() in the find() as opposed to the inspect()
I have updated the PR so you can see what I mean

**Comment by ubermuda** [comment]
Yes that makes sense.

**Comment by ubermuda** [comment]
I guess we can close this now?

**Comment by Boran** [comment]
Tes!
