### ISSUE TITLE
ContainerManager->interact()

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#82]
How is this feature used?
Should a script like:
$container = $manager->find('mycontainer');
$manager->interact($container);

allow one to connect to into a container in the same way as nsenter or docker exec?

**Comment by joelwurtz** [comment]
Interact is like attach but we the ability to send input to the container, doing so you can create a container with a shell process (like /bin/bash) and doing the following stuff : 

```
$stream = $manager->interact($container);
$stream->write("apt-get update \n");
$stream->write("apt-get install php5\n");

echo $stream->receive()['data'];
```

A working example can be found in the tests : https://github.com/stage1/docker-php/blob/master/src/Docker/Tests/Manager/ContainerManagerTest.php#L43

**Comment by Boran** [comment]
Ah, so reading that test (useful doc those tests - thanks), one typically  does a create(), interact()  start() and then write() and read() to the stream.
So this is done on a new container that expects shell input (as you suggest /bin/bash)
Thus, it is not like nsenter or docker exec which are used on existing containers.
