### ISSUE TITLE
Delete obsolete branches

### ISSUE THREAD

**Issue by hacfi** [stage1/docker-php#83]
Trying to polish up this library I kindly request to delete the following branches if you don’t mind:

Merged branches:
- [`feature/chunk_stream_filter`](https://github.com/stage1/docker-php/tree/feature/chunk_stream_filter)

Obsolete branches:
- [`fix`](https://github.com/stage1/docker-php/tree/fix) and [`travis`](https://github.com/stage1/docker-php/tree/travis) - to me it looks like `docker.sh` was "fixed" by https://github.com/stage1/docker-php/commit/7926c4f1#diff-1 
- [`sneakybobito/structure`](https://github.com/stage1/docker-php/tree/sneakybobito/structure) - contains significant changes that I don’t think we can merge anymore as they don’t take the work of the last 6 months into account

**Comment by ubermuda** [comment]
Done!

**Comment by hacfi** [comment]
Thanks :)! It’s a lot of fun working on this library!!

**Comment by ubermuda** [comment]
Happy that you feel that way!

And hopefuly, all the activity around docker-php will motivate me to start working on it again :)
