### ISSUE TITLE
New version needed

### ISSUE THREAD

**Issue by Nek-** [stage1/docker-php#95]
Hello,

The commit https://github.com/stage1/docker-php/commit/f55f61d70e1bcd29d798e1584f7d9557917aae8e is a fix for a critical error. The project need to be tag as new subversion.

Please do it !

Thanks.

**Comment by ubermuda** [comment]
I will do that today or (more likely) tomorrow

**Comment by ubermuda** [comment]
Just tagged `0.4.0`

I bumped the minor version number because there are BC changes in this release (as per the modified semver scheme explained in the README)
