### ISSUE TITLE
Container or image import?

### ISSUE THREAD

**Issue by Boran** [stage1/docker-php#96]
Docker-php has a container export() to a tar file. There does not seem to be a corresponding import() though. Presumably it would be an image import().

Docker command line: http://docs.docker.com/reference/commandline/cli/#import
API, looks like /images/create might be the way to do this? http://docs.docker.com/reference/api/docker_remote_api_v1.16/#create-an-image
- "fromSrc – source to import. The value may be a URL from which the image can be retrieved or - to read the image from the request body."

Has anyone looked into this? An branches around with such a function?
In ImageManager.php, pull() uses /create, it would be similar to that but feeding the tar file into the request body?

**Comment by joelwurtz** [comment]
closed in #147
